# Jekyll configuration
name: Le blog de la famille Tomate
title: Le blog de la famille Tomate
email: bruno@lagrappe.net
description: Site de notes sur la musique, les voyages et d'autres sujets de la famille tomate.

timezone: Europe/Paris

# url is currently only used only for the RSS feed in feed.xml
url: https://www.lagrappe.net

baseurl: "" # the subpath of your site, e.g. /blogdd
twitter_username: bam_thomas
github_username:  bamthomas
github: 'bamthomas/lagrappe'

# Build settings
markdown: kramdown
theme: minima
permalink: /:title/
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag

pagination:
  enabled: true
  per_page: 9
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

exclude: ['README.md', 'LICENSE', '*.sh', '.circleci']
encoding: utf-8
